{
 "title": "FastTechFoods - Monitoramento de APIs",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Latência Média por Controller",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (controller) (rate(http_request_duration_seconds_sum[1m])) / sum by (controller) (rate(http_request_duration_seconds_count[1m]))"
    }
   ]
  },
  {
   "title": "Erros HTTP (4xx/5xx)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "req/s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_received_total{code=~\"4..|5..\"}[1m]))"
    }
   ]
  },
  {
   "title": "Total de Requisições por Status",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "req/s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (code) (rate(http_requests_received_total[1m]))"
    }
   ]
  },
  {
   "title": "Top 5 Endpoints por Tráfego",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "req/s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(5, sum by (endpoint) (rate(http_requests_received_total[1m])))"
    }
   ]
  }
 ]
}